services:
  frontend:
    build:
      context: ./docs/frontend
      dockerfile: Dockerfile
    container_name: erp-frontend
    ports:
      - "8000:3000" # im Container läuft Nuxt auf Port 3000
    env_file:
      - ./docs/frontend/.env
    networks:
      - erp-dev-network

  backend:
    build:
      context: ./docs/backend
      dockerfile: Dockerfile
    container_name: erp-backend
    ports:
      - "3333:3333" # AdonisJS launched intern auf 3333
    env_file:
      - ./docs/backend/.env
    networks:
      - erp-dev-network

networks:
  erp-dev-network:
    driver: bridge
