services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: erp-frontend
    ports:
      - "8000:8000" 
    env_file:
      - ./src/frontend/.env
    networks:
      - erp-dev-network
    volumes:
      - ./src/backend/.env:/src/.env
    environment:
    - API_BASE_URL=http://erp-backend:3333


  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: erp-backend
    ports:
      - "3333:3333"
    env_file:
      - ./src/backend/.env
    networks:
      - erp-dev-network
    volumes:
      - ./src/backend/.env:/src/.env

networks:
  erp-dev-network:
    driver: bridge
